### ISSUE TITLE
Strong typedefs

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#103]
There should be a feature like Haskell's `newtype` that creates a type that's representationally identical to another, but has a distinct type.

**Comment by ghost** [comment]
Would a new keyword be necessary? Maybe reuse define e.g.
<code>define MyInt = int32;</code>

<code>[T,U when Integer?(T,U)] //overide predicate of original
define MyRecord[T,U] = OriginalRecord[T,U];</code>

or would that be too confusing?

What about printed name formatting in compiler output - maybe something like: 
<code>MyInt<Int32></code>

**Comment by jckarter** [comment]
Overloading `define` doesn't seem like a good idea. My plan was to have something along the lines of `newtype A = B;`.
I think the printed name should be formatted normally, the same as any other symbol.

**Comment by ghost** [comment]
Strong typedef implementation "newtype" added in #388
