### ISSUE TITLE
Bogus debug location info

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#105]
With the following test program:

```
record Foo (i:Int, j:Int);

incr(a, n) {
    a += n;
}

main() {
    var x = Foo(0,0);

    println(x);
    incr(x.i, 1);
    println(x);
    incr(x.j, 1);
    println(x);
    incr(x.i, 1);
    println(x);
    incr(x.j, 1);
    println(x);
}
```

I got the following while poking around with gdb:

```

% gdb bar       
GNU gdb 6.3.50-20050815 (Apple version gdb-1708) (Mon Aug  8 20:32:45 UTC 2011)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin"...Reading symbols for shared libraries .. done

(gdb) run
Starting program: /Users/joe/Documents/Code/others/clay/bar 
Reading symbols for shared libraries +........................ done
Foo(0, 0)
Foo(1, 0)
Foo(1, 1)
Foo(2, 1)
Foo(2, 2)

Program exited normally.
(gdb) break bar.clay:7
Breakpoint 1 at 0x100001b0f: file bar.clay, line 7.
(gdb) run
Starting program: /Users/joe/Documents/Code/others/clay/bar 

Breakpoint 1, clay main() () at bar.clay:68
Line number 68 out of range; bar.clay has 19 lines.
```

**Comment by ghost** [comment]
For information I got the following with GDB 7.3.1 on x86_64 Archlinux.

<pre><code>$ gdb bar
GNU gdb (GDB) 7.3.1
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/jeremy/Dev/clay/projects/tests/bar...done.
(gdb) run
Starting program: /home/jeremy/Dev/clay/projects/tests/bar 
Foo(0, 0)
Foo(1, 0)
Foo(1, 1)
Foo(2, 1)
Foo(2, 2)
[Inferior 1 (process 16863) exited normally]
(gdb) break bar.clay:7
Breakpoint 1 at 0x4011bf: file bar.clay, line 7.
(gdb) run
Starting program: /home/jeremy/Dev/clay/projects/tests/bar 

Breakpoint 1, clay main() ()
    at /home/opt/clay/bin/../lib/lib-clay/records/records.clay:68
68      ..recordFields(returned) <-- ..args;
(gdb) 
</code></pre>

**Comment by jckarter** [comment]
Maybe this problem and the other one with source file locations are specific to Apple gdb then.

**Comment by jckarter** [comment]
@Blei is still seeing problems with invalid location information

**Comment by jckarter** [comment]
calls to externals and switch statements were noted as being particularly bad

**Comment by jckarter** [comment]
looks like there are some bugs to work out in type info:

```

(gdb) p *'io.files.stderr'.ptr.ptr
$3 = {
  refCount = 1, 
  value = {
    file = {
      handle = 2, 
      owned = false
    }, 
    readBuffer = Unexpected type (2) encountered for integer constant.
```

**Comment by jckarter** [comment]
Latest batch of fixes seem to have mitigated this. We can open new tickets if more problems surface.
