### ISSUE TITLE
In-module test library

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#131]
The current options for testing Clay code all kind of suck. A better option would be something more like D or Rust's in-line testing support. A `test.module` module could provide a `testMain` function that looks through the main module for member functions beginning with `TEST_` and returning `Bool`, and execute all of those functions. The compiler frontend could then be given a `-main=testMain` flag to set a custom entry point.

```
// sum.clay
public import test.module.(testMain);

in sum;

sum(xs) = reduce(add, 0, xs);

TEST_empty_sum() = sum(Vector[Int]()) == 0;
TEST_single_sum() = sum(Vector[Int](1)) == 1;
TEST_multi_sum() = sum(Vector[Int](1,2,3)) == 6;
```

```
clay -main=testMain -run sum.clay
```

**Comment by jckarter** [comment]
@agemogolk IIRC you were investigating compile-time performance for the test module. Did you have any leads on where the time was being spent?

**Comment by ghost** [comment]
Yes i did have a brief look into it. The static for performance issue contributed as did the heavy use of lambdas, however nothing really stood out in profiling reports (beyond the usual ref counting stuff). Are you looking at test module performance or general compiler performance? There seems to have been a performance regression during the last week (110 s up to 260 s for test suite).

**Comment by jckarter** [comment]
I haven't noticed an overall regression recently—are you comparing debug to release builds or anything like that? I was mostly interested in test module performance in particular, because having the test module add significantly to compile time discourages its use, and testing should be as painless as possible.

**Comment by ghost** [comment]
Yeah I realised I'd come back to a debug build. Currently failing 4 threads
tests though, looks like generated linux 64 bindings are the issue, I'll

## investigate that further tomorrow.

_From:_ "Joe Groff" notifications@github.com
_To:_ "jckarter/clay" clay@noreply.github.com
_CC:_ "agemogolk" agemogolk@gmail.com
_Sent:_ 22 October 2012 23:16
_Subject:_ Re: [clay] In-module test library (#131)

I haven't noticed an overall regression recently—are you comparing debug to
release builds or anything like that? I was mostly interested in test
module performance in particular, because having the test module add
significantly to compile time discourages its use, and testing should be as
painless as possible.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jckarter/clay/issues/131#issuecomment-9682850.

**Comment by ghost** [comment]
Profiling output from compilation of test/module/main.clay

```
Overhead  Command        Shared Object
# ........  .......  ...................  ....................................................................................
#
     5.49%     clay  libc-2.16.so         [.] _int_malloc
     2.00%     clay  libc-2.16.so         [.] malloc
     1.99%     clay  libc-2.16.so         [.] _int_free
     1.46%     clay  clay                 [.] (anonymous namespace)::CallAnalyzer::analyzeCall(llvm::CallSite)
     1.46%     clay  libc-2.16.so         [.] __memcmp_sse4_1
     1.07%     clay  clay                 [.] llvm::InstCombiner::DoOneIteration(llvm::Function&, unsigned int)
     1.05%     clay  clay                 [.] llvm::StringMapImpl::FindKey(llvm::StringRef) const
     1.05%     clay  clay                 [.] clay::computeLineCol(clay::Location const&, int&, int&, int&)
     1.01%     clay  clay                 [.] llvm::AttrListPtr::getAttributes(unsigned int) const
     1.01%     clay  clay                 [.] llvm::Function::getIntrinsicID() const
     0.96%     clay  libc-2.16.so         [.] __strlen_sse2_pminub
     0.95%     clay  clay                 [.] clay::matchInvoke(clay::Pointer<clay::Overload>, clay::Pointer<clay::Object>, ll
     0.93%     clay  clay                 [.] llvm::SmallPtrSetImpl::insert_imp(void const*)
     0.90%     clay  clay                 [.] clay::staticType(clay::Pointer<clay::Object>)
     0.88%     clay  clay                 [.] llvm::Use::getImpliedUser() const
     0.86%     clay  clay                 [.] llvm::ValueHandleBase::AddToUseList()
     0.82%     clay  libstdc++.so.6.0.17  [.] operator new(unsigned long)
     0.75%     clay  libc-2.16.so         [.] malloc_consolidate
     0.73%     clay  clay                 [.] clay::lookupInvokeSet(clay::Pointer<clay::Object>, llvm::ArrayRef<clay::Pointer<
     0.70%     clay  clay                 [.] llvm::ValueHandleBase::RemoveFromUseList()
     0.63%     clay  libc-2.16.so         [.] free
     0.59%     clay  libc-2.16.so         [.] __memset_sse2
     0.55%     clay  clay                 [.] llvm::isInstructionTriviallyDead(llvm::Instruction*)
     0.53%     clay  libc-2.16.so         [.] __memcpy_ssse3_back
     0.51%     clay  clay                 [.] llvm::StringRef::StringRef(char const*)
     0.51%     clay  clay                 [.] clay::clone(clay::Pointer<clay::Expr>)
     0.50%     clay  clay                 [.] llvm::ComputeMaskedBits(llvm::Value*, llvm::APInt&, llvm::APInt&, llvm::TargetDa
     0.50%     clay  [kernel.kallsyms]    [k] page_fault
     0.46%     clay  clay                 [.] clay::tokenize(clay::Pointer<clay::Source>, unsigned long, unsigned long, std::v
```

**Comment by jckarter** [comment]
I saw you put some work into implementing a `test.minimal` mode for the `test` module. I expanded it to disable parameter parsing in addition to color output, and compilation time for the `test` tests goes down by about 40% for me now.
