### ISSUE TITLE
Archlinux AUR pkg build fails with issue#147

### ISSUE THREAD

**Issue by ghost** [jckarter/clay#158]
Output from pkg build attempt with make VERBOSE=1

<pre><head>
==> Making package: clay-git 0.1-2 (Fri Jan  6 22:28:25 GMT 2012)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving Sources...
==> Extracting Sources...
==> Entering fakeroot environment...
==> Starting build()...
==> getting clay
Cloning into 'clay'...
remote: Counting objects: 43917, done.
remote: Compressing objects: 100% (19565/19565), done.
remote: Total 43917 (delta 19755), reused 43672 (delta 19526)
Receiving objects: 100% (43917/43917), 21.38 MiB | 693 KiB/s, done.
Resolving deltas: 100% (19755/19755), done.
==> GIT checkout done or server timeout
==> Start building Clay
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/lib/colorgcc/bin/gcc
-- Check for working C compiler: /usr/lib/colorgcc/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/colorgcc/bin/c++
-- Check for working CXX compiler: /usr/lib/colorgcc/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Subversion: /usr/bin/svn (found version "1.7.2")
-- Found Git: /usr/bin/git 
-- Found PythonInterp: /usr/bin/python (found version "3.2.2")
-- Looking for clang_getTypedefDeclUnderlyingType
-- Looking for clang_getTypedefDeclUnderlyingType - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build
/usr/bin/cmake -H/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay -B/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/CMakeFiles /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
make -f compiler/src/CMakeFiles/clay.dir/build.make compiler/src/CMakeFiles/clay.dir/depend
make[2]: Entering directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
/usr/bin/cmake -E cmake_progress_report /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/CMakeFiles 24
[  3%] Generating clay.hpp.gch
cd /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src && /usr/lib/colorgcc/bin/c++ -x c++-header /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/compiler/src/clay.hpp -I/usr/include -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -fno-exceptions -fno-rtti -fPIC -Woverloaded-virtual -Wcast-qual -fno-rtti -DNDEBUG -o clay.hpp.gch
cd /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/compiler/src /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/CMakeFiles/clay.dir/DependInfo.cmake --color=
Dependee "/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/CMakeFiles/clay.dir/DependInfo.cmake" is newer than depender "/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/CMakeFiles/clay.dir/depend.internal".
Dependee "/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/CMakeFiles/clay.dir/depend.internal".
Scanning dependencies of target clay
make[2]: Leaving directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
make -f compiler/src/CMakeFiles/clay.dir/build.make compiler/src/CMakeFiles/clay.dir/build
make[2]: Entering directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
/usr/bin/cmake -E cmake_progress_report /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/CMakeFiles 1
[  7%] Building CXX object compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o
cd /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src && /usr/lib/colorgcc/bin/c++    -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2    -I/usr/include  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -fno-exceptions -fno-rtti -fPIC -Woverloaded-virtual -Wcast-qual -fno-rtti -DNDEBUG -include /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/clay.hpp -o CMakeFiles/clay.dir/analyzer.cpp.o -c /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/compiler/src/analyzer.cpp
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: /home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build/compiler/src/clay.hpp: No such file or directory
compilation terminated.
make[2]: *** [compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o] Error 1
make[2]: Leaving directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
make[1]: *** [compiler/src/CMakeFiles/clay.dir/all] Error 2
make[1]: Leaving directory `/home/jeremy/Dev/clay/projects/clay/misc/archlinux/clay-git/src/clay/build'
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
</head></pre>

**Comment by jckarter** [comment]
I guess Arch's package builder throws in these flags somewhere:

```
  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2
```

**Comment by ghost** [comment]
Yeah, i'm just looking to see if I can force the build flags. Should be pretty simple.

**Comment by ghost** [comment]
OK, I think i've fixed it - just compiling. When i've tested the pkg i'll upload and close this issue.

**Comment by jckarter** [comment]
Well, I think the PCH rule should probably be modified to include those flags. I'm not sure what cmake variable they come from, though.

**Comment by ghost** [comment]
I'll take a look at archlinux build flags, but for now the package seems to be working.
