### ISSUE TITLE
-g fails on linux

### ISSUE THREAD

**Issue by ghost** [jckarter/clay#160]
Debug symbol info compiler switch causes following error:

<pre><head>
clay -g main.clay
clay: /home/jeremy/Dev/clay/projects/clay_aur/llvm-clay-git/src/llvm/lib/Analysis/DIBuilder.cpp:80: <br> void llvm::DIBuilder::createCompileUnit(unsigned int, llvm::StringRef, llvm::StringRef, llvm::StringRef, <br>  bool, llvm::StringRef, unsigned int): Assertion `Lang <= dwarf::DW_LANG_D && Lang >= dwarf::DW_LANG_C89 && <br> "Invalid Language tag"' failed.
Aborted
</head></pre>

**Comment by ghost** [comment]
Looks like it has something to do with my llvm install, i'll reinstall and try again.

**Comment by jckarter** [comment]
Looks like LLVM assert builds are overly restrictive when it comes to language tags. It should also admit language tags in the user region.

**Comment by jckarter** [comment]
Here's an LLVM patch that fixes the problem:

https://github.com/jckarter/llvm-3.0/commit/ddf85620afc7a04617e4184fe7a555471a54345f

I can make Clay pretend to be C++ or something so it works with vanilla LLVM 3.0 in the meantime.

**Comment by ghost** [comment]
Not sure if this is an issue:

This compiles and runs OK:

clay main.clay -lm -run > out.txt

However, including debug symbols gives:

clay -g main.clay -lm -run > out.txt
pseudo instructions should be removed before code emission
UNREACHABLE executed at 
/tmp/yaourt-tmp-jeremy/aur-llvm-clay-git/src/llvm/lib/Target/X86/X86CodeEmitter.cpp:735!
Stack dump:
0.    Running pass 'X86 Machine Code Emitter' on function 
'@"numbers.floats.floats.floatFromBits(UInt64) Float64 clay"'
Aborted

**Comment by jckarter** [comment]
`-run` is pretty buggy since `llvm::ExecutionEngine` is a total hack. The frontend should maybe refuse to accept `-g` and `-run` together.

**Comment by jckarter** [comment]
Another thing we could try is enabling `JITEmitDebugInfo` to see if that helps:

http://llvm.org/docs/doxygen/html/classllvm_1_1TargetOptions.html#a2d997cfe1f0dd48066f5df7686350e9e
