### ISSUE TITLE
[bindgen] doesn't correctly generate some typedefs

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#198]
Taken from the headers that are distributed with clang 3.0 (stddef.h):

``` c
typedef __typeof__(((int*)0)-((int*)0)) ptrdiff_t;
typedef __typeof__(sizeof(int)) size_t;
```

This produces

```
alias ptrdiff_t = Opaque /* unknown NoDeclFound  */;

alias size_t = Opaque /* unknown NoDeclFound  */;
```

which is unfortunate if anyone decides to generate the libc or unix bindings with the clang headers, as everything will explode with this `size_t`. Works with the gcc headers though.

**Comment by jckarter** [comment]
@Blei 9267976 fixes a sample file with a **typeof** typedef for me. Let me know if it works for the clang headers in general.

**Comment by Blei** [comment]
I tried regenerating the unix and libc bindings with the clay headers, everything works. Thanks!
