### ISSUE TITLE
Linking of clay fails on Linux x86_64

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#20]
The problem is, that the -ldl flag is included in the LLVM_LDFLAGS and not in the LLVM_LIBS. The LDFLAGS are added to the front of the command line, but the -ldl should be at the end to link correctly. (The linker command can be seen in ./build/compiler/src/CMakeFiles/clay.dir/link.txt).

As a quick fix/hack, it is possible to add the dl library explicitely in the same way as the rt library (in ./compiler/src/CMakeLists.txt).

**Comment by Blei** [comment]
Ah, this is when compiling the v0.1 branch with LLVM & clang from SVN.

**Comment by jckarter** [comment]
That's annoying. llvm-config was also forcing -O3 on me in the --cflags (a pain when you're trying to debug anything). Hopefully they'll fix llvm-config up a bit before the release.

**Comment by jckarter** [comment]
@Blei regarding your comment about compile performance on IRC; it looks like 3.0's llvm-config includes `-D_DEBUG` in the cxxflags whereas 2.9 used `-DNDEBUG`. Hacking NDEBUG into the cxxflags gets the compiler speed back to baseline.

**Comment by jckarter** [comment]
Looks like @agemogolk had the same issue: https://github.com/agemogolk/clay/commit/7caae1f3258ea9ac1848fdb8cbb61d140d7cfa27 I'll push a fix.

**Comment by ghost** [comment]
It seems to have been resolved with your latest commits. v0.1 builds fine on my x86_64 including clayfix.

**Comment by jckarter** [comment]
Good to hear. Maybe it was fixed in LLVM svn recently.

**Comment by ghost** [comment]
Oh yeah, I did do do an llvm/clang update last night (3.1svn).  That was probably it.
