### ISSUE TITLE
math.pow() produces compile-time error

### ISSUE THREAD

**Issue by adob** [jckarter/clay#200]
Calling math.pow(3,3) produces a missing overload error.
Calling math.pow(3.0, 3.0) produces an undefined name error from within pow() implementation.

Using version 0.1.

**Comment by jckarter** [comment]
Clay in general does not perform conversions. pow is a floating-point operation, so it requires floating-point operands.

**Comment by jckarter** [comment]
Sorry, missed the second line. Try `-Dmath.Mode=libm` to use the libc implementation as a workaround. The native math implementation is still a bit green.

**Comment by jckarter** [comment]
@agemogolk `powdb` is undefined at math/native/pow_std.clay line 4091. Where is it supposed to come from?

**Comment by ghost** [comment]
See pull request #201

**Comment by jckarter** [comment]
Fixed by @agemogolk in #201. Thanks.

**Comment by adob** [comment]
Thanks for fixing this so quickly!
