### ISSUE TITLE
Operator names fail lookup in imports and qualified names

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#243]
I get undefined name errors when attempting to import and use operator names as identifiers. Here's a test case that ought to work:

foo.clay:

```
(~~)(a, b) { println("~~"); }
```

main.clay:

```
import foo;
import foo.((~~));

(**)(a, b) { println("**"); }

overload (~~)(a:Float, b:Float) { println("~~ Float"); }
overload foo.(~~)(a:Double, b:Double) { println("~~ Double"); }

operatorAsStaticArg1(#(~~)) { println("#(~~) 1"); }
operatorAsStaticArg2(#foo.(~~)) { println("#(~~) 2"); }

main() {
    1 ** 2;
    1 ~~ 2;
    1f ~~ 2f;
    1. ~~ 2.;

    (**)(1, 2);
    (~~)(1, 2);
    (~~)(1f, 2f);
    (~~)(1., 2.);

    foo.(~~)(1, 2);
    foo.(~~)(1f, 2f);
    foo.(~~)(1., 2.);

    operatorAsStaticArg1((~~));
    operatorAsStaticArg1(foo.(~~));
    operatorAsStaticArg2((~~));
    operatorAsStaticArg2(foo.(~~));
}
```

**Comment by jckarter** [comment]
@agemogolk If you have time, could you look at this? I've pushed the failing test case to my `issue-243` branch.

**Comment by ghost** [comment]
The test works for me with the exception of trying to define infix operators with no return value which are not yet supported (but simple enough to implement). Is there any way import lookup could be platform specific?

**Comment by ghost** [comment]
I've been looking at various ways to handle unary operators and generally improve the operator system, it really needs more integrated support in the compiler to be effective/efficient. Something like tagging an 'operator' symbol when parsed and identify it using an Operator? prim_op would make things simpler on the evaluation end.

**Comment by jckarter** [comment]
You're right, it does work, I was just stupidly trying to run the test without setting the search path correctly. Allowing binary operators to return zero or multiple values would be nice. An `Operator?` primitive sounds useful; so does a general `Symbol?` primitive.

**Comment by ghost** [comment]
I've already put in a Symbol? and Procedure? primitive (not pushed yet). However i'm struggling to find a way of tagging an operator symbol when defined indirectly from an alias binding (works fine for an operator defined function e.g.<code> (**)(a,b){...} </code>).

**Comment by jckarter** [comment]
Do operator symbols actually need to be treated differently from other symbols at all?

**Comment by ghost** [comment]
Technically no, but reducing a prefix/infix operator list in which items 
can be anything doesn't seem to be practical (as unary/binary operator 
symbols may be operated on by other prefix/infix operators . . . etc . . 
. ).

**Comment by jckarter** [comment]
Unfortunately, because of aliases and import names, I don't think it's possible or desirable to differentiate operators. How are you envisioning the desugaring of prefix operators? I don't think a fancy desugaring is necessary; wouldn't `prefix(op, argument)` be sufficient?

**Comment by ghost** [comment]
Thought that might be the case. I was trying to integrate prefix ops into the same operatorCall as binary ops and reduce the whole list in one go - gets very messy trying to cover all corner cases. Now I think a better solution is to generate separate calls for prefix lists to remove operator/operand ambiguity.

**Comment by jckarter** [comment]
One minor nitpick: I noticed that operators' internal names include the parens, whereas I would expect them not to. I would expect, for example, `fieldRef(module, "+")` to work, not `fieldRef(module, "(+)")`.

**Comment by ghost** [comment]
Yeah you're right, no need for parentheses. Fixed. I have prefix ops 
working and will put in a pull request shortly.
