### ISSUE TITLE
bindgen generates duplicate definitions from linux libc headers

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#265]
`pthread_mutex_s` gets bound twice

**Comment by jckarter** [comment]
Test case:

```
typedef union {
    struct x { int y; };            
} z;
```

generates:

```
record Struct_x (
    y : Int,
);

alias z = Union[
];

record Struct_x (
    y : Int,
);
```

**Comment by jckarter** [comment]
@crabtw You might check if rust-bindgen has this same problem (unless rust is OK with duplicate declarations).

**Comment by crabtw** [comment]
@jckarter rust-bindgen has the same problem. I have fixed. Thank you.
