### ISSUE TITLE
wrong code with llvm intrinsic and debug information

### ISSUE THREAD

**Issue by MartinNowak** [jckarter/clay#283]
``` clay
import simd.*;

external ("llvm.x86.sse2.sqrt.sd", llvm)
    x86_sqrtsd(a: Vec[Double,2]): Vec[Double,2];

sqrt(x: Double) = x86_sqrtsd(Vec[Double,2](x, x));

main() { sqrt(1.0); }
```

`clay -g bug.clay`

Invalid user of intrinsic instruction!
void ()\* bitcast (<2 x double> (<2 x double>)\* @llvm.x86.sse2.sqrt.sd to void ()*)
Broken module found, compilation aborted!

PLATFORM: x86_64-unknown-freebsd9.0

**Comment by jckarter** [comment]
Yeah, unfortunately the compiler currently codegens all externals as function pointer objects, which LLVM doesn't like with intrinsics. The optimizer normally eliminates the function pointer, but `-g` or `-O0` disables optimization and breaks compilation. If you need it work right now, a kind of crummy workaround is to use `__llvm__` to interface with the intrinsic:

```
__llvm__ { declare <2 x double> @llvm.x86.sse2.sqrt.sd(<2 x double> %x) }

x86_sqrtsd(a:Vec[Double,2]) --> out:Vec[Double,2] __llvm__ {
    %av = load <2 x double>* %a
    %outv = call <2 x double> @llvm.x86.sse2.sqrt.sd(<2 x double> %av)
    store <2 x double> %outv, %out
    ret i8* null
}
```

**Comment by jckarter** [comment]
I implemented an `__intrinsics__` module which contains symbols for calling LLVM intrinsics. It doesn't try to use function pointers so it doesn't suffer this problem. The example in the issue can now be written as:

```
import simd.*;
import __intrinsics__.(x86_sse2_sqrt_sd as x86_sqrtsd);

sqrt(x: Double) = x86_sqrtsd(Vec[Double,2](x, x));

main() { sqrt(1.0); }
```
