### ISSUE TITLE
Clay does not build "out of the box" on Debian Unstable

### ISSUE THREAD

**Issue by russel** [jckarter/clay#294]
I have ensured I have Clang and LLVM installed, 3.1 not 3.0 on my otherwise fairly standard Debian Unstable.

|> git pull
Already up-to-date.

|> mkdir Build

|> cd Build/

|> cmake -G "Unix Makefiles" ../
-- The C compiler identification is GNU 4.7.1
-- The CXX compiler identification is GNU 4.7.1
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Subversion: /usr/bin/svn (found version "1.7.5") 
-- Found Git: /usr/bin/git (found version "1.7.10.4") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.3") 
-- Looking for clang_getTypedefDeclUnderlyingType
-- Looking for clang_getTypedefDeclUnderlyingType - not found.
-- libclang is missing, so bindgen will not be built.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Checkouts/Git/Git/Clay/Build

CMake is not finding Clang even though it is installed using the Debian packages.

Adding LLVM_DIR=/usr/lib/llvm-3.1 makes no difference

**Comment by jckarter** [comment]
LLVM 3.1 has some problems with GCC 4.7. Can you try 4.6 or an older GCC?

**Comment by jckarter** [comment]
Also, does the Debian clang package include libclang.so, or do you need an additional package for it? Did you also install the -dev package?

**Comment by jckarter** [comment]
Note that the "bindgen will not be built" message isn't a fatal error. It looks like cmake still completely successfully, so you should be able to build the compiler.

**Comment by russel** [comment]
The problem witht he configuration is deeper than just the bindgen message:

|> make
Scanning dependencies of target clay
[  2%] Building CXX object compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o
In file included from /home/Checkouts/Git/Git/Clay/compiler/src/analyzer.cpp:2:0:
/home/Checkouts/Git/Git/Clay/compiler/src/clay.hpp:28:34: fatal error: llvm/ADT/SmallString.h: No such file or directory
compilation terminated.
make[2]: **\* [compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o] Error 1
make[1]: **\* [compiler/src/CMakeFiles/clay.dir/all] Error 2
make: **\* [all] Error 2

**Comment by russel** [comment]
I made sure all the clang packages were installed exactly to cover the point you were worrying about:

|> dpkg -l _clang_
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                           Version              Architecture         Description
+++-==============================-====================-====================-==================================================================
ii  clang                          3.1-8                amd64                Low-Level Virtual Machine (LLVM), C language family frontend
un  clang-3.1                      <none>                                    (no description available)
ii  libclang-common-dev            3.1-8                amd64                clang library - Common development package
ii  libclang-dev                   3.1-8                amd64                clang library - Development package
ii  libclang1                      3.1-8                amd64                clang library

The libraries are all in place:

|> ll /usr/lib/_clang_
-rw-r--r-- 1 root root  970034 Jun 27 23:24 /usr/lib/libclang.a
-rw-r--r-- 1 root root  614578 Jun 27 23:24 /usr/lib/libclangAnalysis.a
-rw-r--r-- 1 root root 2294180 Jun 27 23:24 /usr/lib/libclangARCMigrate.a
-rw-r--r-- 1 root root 3529058 Jun 27 23:24 /usr/lib/libclangAST.a
-rw-r--r-- 1 root root 1540200 Jun 27 23:24 /usr/lib/libclangBasic.a
-rw-r--r-- 1 root root 3151334 Jun 27 23:24 /usr/lib/libclangCodeGen.a
-rw-r--r-- 1 root root 1041600 Jun 27 23:24 /usr/lib/libclangDriver.a
-rw-r--r-- 1 root root   54630 Jun 27 23:24 /usr/lib/libclangEdit.a
-rw-r--r-- 1 root root 1282198 Jun 27 23:24 /usr/lib/libclangFrontend.a
-rw-r--r-- 1 root root   13808 Jun 27 23:24 /usr/lib/libclangFrontendTool.a
-rw-r--r-- 1 root root  782602 Jun 27 23:24 /usr/lib/libclangLex.a
-rw-r--r-- 1 root root 1185224 Jun 27 23:24 /usr/lib/libclangParse.a
-rw-r--r-- 1 root root  882320 Jun 27 23:24 /usr/lib/libclangRewrite.a
-rw-r--r-- 1 root root 6290544 Jun 27 23:24 /usr/lib/libclangSema.a
-rw-r--r-- 1 root root 1336478 Jun 27 23:24 /usr/lib/libclangSerialization.a
lrwxrwxrwx 1 root root      13 Jun 27 23:24 /usr/lib/libclang.so -> libclang.so.1
-rw-r--r-- 1 root root 9954888 Jun 27 23:24 /usr/lib/libclang.so.1
-rw-r--r-- 1 root root 3066836 Jun 27 23:24 /usr/lib/libclangStaticAnalyzerCheckers.a
-rw-r--r-- 1 root root 1852500 Jun 27 23:24 /usr/lib/libclangStaticAnalyzerCore.a
-rw-r--r-- 1 root root  316994 Jun 27 23:24 /usr/lib/libclangStaticAnalyzerFrontend.a
-rw-r--r-- 1 root root   87114 Jun 27 23:24 /usr/lib/libclangTooling.a

**Comment by russel** [comment]
I tried with GCC 4.6 but same result, so this isn't a compiler problem more a configuration problem -- I guess:

|> rm -r *

|> CC=/usr/bin/gcc-4.6 CXX=/usr/bin/g++-4.6 LLVM_DIR=/usr/lib/llvm-3.1 cmake -G "Unix Makefiles" ../
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc-4.6
-- Check for working C compiler: /usr/bin/gcc-4.6 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.6
-- Check for working CXX compiler: /usr/bin/g++-4.6 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Subversion: /usr/bin/svn (found version "1.7.5") 
-- Found Git: /usr/bin/git (found version "1.7.10.4") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.3") 
-- Looking for clang_getTypedefDeclUnderlyingType
-- Looking for clang_getTypedefDeclUnderlyingType - not found.
-- libclang is missing, so bindgen will not be built.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Checkouts/Git/Git/Clay/Build

|> CC=/usr/bin/gcc-4.6 CXX=/usr/bin/g++-4.6 LLVM_DIR=/usr/lib/llvm-3.1 make
Scanning dependencies of target clay
[  2%] Building CXX object compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o
In file included from /home/Checkouts/Git/Git/Clay/compiler/src/analyzer.cpp:2:0:
/home/Checkouts/Git/Git/Clay/compiler/src/clay.hpp:28:34: fatal error: llvm/ADT/SmallString.h: No such file or directory
compilation terminated.
make[2]: **\* [compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o] Error 1
make[1]: **\* [compiler/src/CMakeFiles/clay.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jckarter** [comment]
What does `make VERBOSE=1` look like? If `llvm-config` is on your path and `llvm-config --libs` and `llvm-config --cxxflags` correctly refer to the 3.1 libs, the `LLVM_DIR` setting shouldn't be needed. The cmake script just uses `${LLVM_DIR}/bin` to try to find `llvm-config`.

**Comment by russel** [comment]
```
|> make VERBOSE=1
/usr/bin/cmake -H/home/Checkouts/Git/Git/Clay -B/home/Checkouts/Git/Git/Clay/Build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/Checkouts/Git/Git/Clay/Build/CMakeFiles /home/Checkouts/Git/Git/Clay/Build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/Checkouts/Git/Git/Clay/Build'
make -f compiler/src/CMakeFiles/clay.dir/build.make compiler/src/CMakeFiles/clay.dir/depend
make[2]: Entering directory `/home/Checkouts/Git/Git/Clay/Build'
cd /home/Checkouts/Git/Git/Clay/Build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/Checkouts/Git/Git/Clay /home/Checkouts/Git/Git/Clay/compiler/src /home/Checkouts/Git/Git/Clay/Build /home/Checkouts/Git/Git/Clay/Build/compiler/src /home/Checkouts/Git/Git/Clay/Build/compiler/src/CMakeFiles/clay.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/Checkouts/Git/Git/Clay/Build'
make -f compiler/src/CMakeFiles/clay.dir/build.make compiler/src/CMakeFiles/clay.dir/build
make[2]: Entering directory `/home/Checkouts/Git/Git/Clay/Build'
/usr/bin/cmake -E cmake_progress_report /home/Checkouts/Git/Git/Clay/Build/CMakeFiles 1
[  2%] Building CXX object compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o
cd /home/Checkouts/Git/Git/Clay/Build/compiler/src && /usr/bin/g++-4.6      -DNDEBUG -o CMakeFiles/clay.dir/analyzer.cpp.o -c /home/Checkouts/Git/Git/Clay/compiler/src/analyzer.cpp
In file included from /home/Checkouts/Git/Git/Clay/compiler/src/analyzer.cpp:2:0:
/home/Checkouts/Git/Git/Clay/compiler/src/clay.hpp:28:34: fatal error: llvm/ADT/SmallString.h: No such file or directory
compilation terminated.
make[2]: *** [compiler/src/CMakeFiles/clay.dir/analyzer.cpp.o] Error 1
make[2]: Leaving directory `/home/Checkouts/Git/Git/Clay/Build'
make[1]: *** [compiler/src/CMakeFiles/clay.dir/all] Error 2
make[1]: Leaving directory `/home/Checkouts/Git/Git/Clay/Build'
make: *** [all] Error 2
```

**Comment by russel** [comment]
```
|> llvm-config --libs
-bash: llvm-config: command not found

|> llvm-config --cxxflags
-bash: llvm-config: command not found


|> /usr/lib/llvm-3.1/bin/llvm-config --libs
-lLLVMAsmParser -lLLVMInstrumentation -lLLVMLinker -lLLVMArchive -lLLVMBitReader -lLLVMDebugInfo -lLLVMJIT -lLLVMipo -lLLVMVectorize -lLLVMBitWriter -lLLVMTableGen -lLLVMHexagonCodeGen -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMHexagonAsmPrinter -lLLVMPTXCodeGen -lLLVMPTXDesc -lLLVMPTXInfo -lLLVMPTXAsmPrinter -lLLVMMBlazeCodeGen -lLLVMMBlazeDisassembler -lLLVMMBlazeDesc -lLLVMMBlazeAsmPrinter -lLLVMMBlazeAsmParser -lLLVMMBlazeInfo -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMCellSPUCodeGen -lLLVMCellSPUDesc -lLLVMCellSPUInfo -lLLVMMipsDisassembler -lLLVMMipsAsmParser -lLLVMMipsCodeGen -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMARMDisassembler -lLLVMARMAsmParser -lLLVMARMCodeGen -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMPowerPCCodeGen -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMSparcCodeGen -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86AsmParser -lLLVMX86Disassembler -lLLVMX86Desc -lLLVMX86AsmPrinter -lLLVMX86Info -lLLVMX86Utils -lLLVMMCDisassembler -lLLVMMCParser -lLLVMInterpreter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMMCJIT -lLLVMRuntimeDyld -lLLVMExecutionEngine -lLLVMTarget -lLLVMMC -lLLVMObject -lLLVMCore -lLLVMSupport

|> /usr/lib/llvm-3.1/bin/llvm-config --cxxflags
-I/usr/lib/llvm-3.1/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -Wcast-qual

```

**Comment by jckarter** [comment]
In that case it looks like you have `LLVM_DIR` set correctly. What does running `cmake -LA .` from inside your build directory say?

**Comment by russel** [comment]
Looks like a failing in CMake ?

|> CC=/usr/bin/gcc-4.6 CXX=/usr/bin/g++-4.6 LLVM_DIR=/usr/lib/llvm-3.1 cmake -LA
CMake Error: The source directory "/home/Checkouts/Git/Git/Clay/Build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values
BUILD_BINDGEN:BOOL=True
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_BUILD_TYPE:STRING=
CMAKE_COLOR_MAKEFILE:BOOL=ON
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-4.6
CMAKE_CXX_FLAGS:STRING=
CMAKE_CXX_FLAGS_DEBUG:STRING=-g
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g
CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-4.6
CMAKE_C_FLAGS:STRING=
CMAKE_C_FLAGS_DEBUG:STRING=-g
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g
CMAKE_EXE_LINKER_FLAGS:STRING= 
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_LINKER:FILEPATH=/usr/bin/ld
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
CMAKE_MODULE_LINKER_FLAGS:STRING= 
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_NM:FILEPATH=/usr/bin/nm
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
CMAKE_SHARED_LINKER_FLAGS:STRING= 
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
CMAKE_SKIP_RPATH:BOOL=NO
CMAKE_STRIP:FILEPATH=/usr/bin/strip
CMAKE_USE_RELATIVE_PATHS:BOOL=OFF
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
CPACK_BINARY_DEB:BOOL=OFF
CPACK_BINARY_NSIS:BOOL=OFF
CPACK_BINARY_RPM:BOOL=OFF
CPACK_BINARY_STGZ:BOOL=ON
CPACK_BINARY_TBZ2:BOOL=OFF
CPACK_BINARY_TGZ:BOOL=ON
CPACK_BINARY_TZ:BOOL=ON
CPACK_SOURCE_TBZ2:BOOL=ON
CPACK_SOURCE_TGZ:BOOL=ON
CPACK_SOURCE_TZ:BOOL=ON
CPACK_SOURCE_ZIP:BOOL=OFF
ENABLE_PCH:BOOL=False
GIT_EXECUTABLE:FILEPATH=/usr/bin/git
LLVM_CONFIG:FILEPATH=LLVM_CONFIG-NOTFOUND
LLVM_DIR:PATH=/usr/local
Mercurial_EXECUTABLE:FILEPATH=/usr/bin/hg
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python
Subversion_SVN_EXECUTABLE:FILEPATH=/usr/bin/svn

**Comment by jckarter** [comment]
Yeah, it looks like LLVM_DIR and LLVM_CONFIG didn't get stored in the cache properly. You could try monkey-patching the right values into the cache with `cmake -DLLVM_DIR=/usr/lib/llvm-3.1 -DLLVM_CONFIG=/usr/lib/llvm-3.1/bin/llvm-config .`.

**Comment by jckarter** [comment]
Oh, I see! cmake doesn't take parameters from the shell environment; parameters are set with the `-D` option. `LLVM_DIR=foo cmake` won't do anything. `cmake -DLLVM_DIR=foo` will. (Confusing I know, because it _does_ pay attention to some env vars like `CXX`, `CC`, etc.)

**Comment by jckarter** [comment]
@russel Did you get clay working?

**Comment by russel** [comment]
Using the -D option certainly got a proper configuration clang was found and Clay compiled. Now I just need to find the right CMake incantation to set the correct install location. For me I want the executables in ~/bin.Linux/x86_64 and the libraries in ~/lib.Linux.x86_64

**Comment by jckarter** [comment]
Good to hear. I'll close the ticket then. Re: setting install location, I know -DCMAKE_INSTALL_PREFIX=/foo will set the install prefix for a traditional Unix-hierarchy install with bin/ lib/ etc. subdirectories, but at a glance it doesn't appear that cmake supports something more exotic out of the box. In the worst case you could manually edit clay's CMakeLists.txt files to set the DESTINATION options of the install() rules.

**Comment by russel** [comment]
The projects CMake files have to be written with the ability to set the executable and library locations otherwise it is not possible. This clearly has not happened for Clay. On this topic Autotools and Waf win, SCons comes 3rd, and CMake comes 7th.

As you say though this issue is resolved and correctly marked as such.

I'll just have to write a script to do the install given that CMake s$$$$ so much.
