### ISSUE TITLE
Implicit multiple-value context when function is declared with multiple return types

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#31]
In a function definition like:

```
foo() : Int, Bool = ..bar();
```

The `..` is required. Since the return type declaration `Int, Bool` makes it obvious that multiple returns are wanted, the `..` should be implied, as it is for multiple variable bindings such as `var x, y = bar();`

**Comment by ghost** [comment]
This issue should now be fixed as of commit #323 
e.g.
foo() = integers(#2); // Does not work
jar() = ..integers(#2); // Works
bar() : Int32, Int32 = ..integers(#2); // Works
goo() : Int32, Int32 = integers(#2); // Works

**Comment by jckarter** [comment]
Thanks @agemogolk. I'll close the issue.
