### ISSUE TITLE
support top level ref

### ISSUE THREAD

**Issue by stepancheg** [jckarter/clay#343]
```
import printer.*;

var a = 1;
ref b = a;

main() {
    println(b);
}
```

compilation fails with 'parse error':

```
###############################

var a = 1;
ref b = a;
^

main() {
###############################
tmp.clay(4,0): error: parse error
```

**Comment by jckarter** [comment]
You could use a top-level alias in lieu of a ref.

**Comment by stepancheg** [comment]
Indeed. Thanks.

**Comment by ghost** [comment]
Would top-level ref/forward be useful? Or would it be generally better to limit global vars/refs?

**Comment by jckarter** [comment]
I don't think toplevel `ref` and `forward` are semantically different from top-level aliases, since toplevel values are always lvalues and toplevel references are always valid.

**Comment by ghost** [comment]
OK.
