### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#345]
According to clay.dembits.com there are test failures on win32 and win64:

https://github.com/erg/claybuild-win64/blob/master/testlog.txt
https://github.com/erg/claybuild-win32/blob/master/testlog.txt

**Comment by stepancheg** [comment]
This is my fault. Sorry. I'll provide a patch in a minute.

**Comment by stepancheg** [comment]
Pull request https://github.com/jckarter/clay/pull/346
