### ISSUE TITLE
Recent commit breaks win32 build

### ISSUE THREAD

**Issue by farces** [jckarter/clay#387]
Commit  027abe4a08a323ed796588e21bfdba4d4c6afe50 adds use of llvm::Linker, though CMakeLists.txt WIN32 section wasn't updated to match. As a result main.cpp.obj is linked without LLVMLinker.lib and fails.

Adding `linker` to llvm_map_components_to_libraries(LLVM_LIBS,...) in the root CMakeLists.txt document solves the problem.

**Comment by jckarter** [comment]
Thanks for the report, @farces. I pushed 470b4837d7aa530a4bb08f0faa89a7252c82e251, but I don't have a Windows box to test on right away; does it fix the problem for you?

**Comment by farces** [comment]
Works perfectly :)
