### ISSUE TITLE
clay-bindgen doesn't parse the whole file

### ISSUE THREAD

**Issue by galchinsky** [jckarter/clay#391]
After adding signal.h to lib-clay/libc

https://github.com/galchinsky/clay/blob/74ec43de71d6634cac64097e8d6b91687a644db7/lib-clay/libc/generated/generated.linux.32.clay#L2921

https://github.com/galchinsky/clay/blob/74ec43de71d6634cac64097e8d6b91687a644db7/lib-clay/libc/generated/generated.linux.64.clay#L2433
The files are edited to avoid parse error in commit.

**Comment by stepancheg** [comment]
This is probably due to [this bug fixed](https://github.com/jckarter/clay/commit/ead41ce4b70a6410b92e86e414c47c8116198a16). Please check against master.

**Comment by jckarter** [comment]
@stepancheg Is stderr no longer flushed on exit? If not, it should be (or stderr should be unbuffered), so that errors don't get lost.

**Comment by stepancheg** [comment]
@jckarter
- Both stdout and stderr are flushed on exit
- stdout and stderr are line buffered when output is terminal. It is not the case, JFYI.
- bindgen didn't write to global stdout variable, but rather to stdoutFile() result. stdout variable is flushed on exit (see FlushOnDestroy in io.files), but explicitly created File objects (as well as other OutputStream) must be explicitly flushed.

**Comment by jckarter** [comment]
@galchinsky @stepancheg I see that bindgen now flushes the handle on exit. Is this still a problem, or can the issue be closed?

**Comment by galchinsky** [comment]
I didnt test after merging that fix, and wont be able till weekend, but I think that flushing is the solution. There is another bug though, it was also mentioned on irc. Clang couldnt find some headers without explicit command line param on debian. I m far from pc now and cant give more information

**Comment by galchinsky** [comment]
This may be closed. But I'll create another one

**Comment by jckarter** [comment]
Does it work now, or is there another problem?

**Comment by galchinsky** [comment]
Yeah, #419
