### ISSUE TITLE
evaluator should detect recursion

### ISSUE THREAD

**Issue by stepancheg** [jckarter/clay#394]
```
[when foo()]
foo() = true;

main() {
    foo();
}
```

compiler endlessly prints

```
  rec.clay(1,9):
    foo()
  rec.clay(1,9):
    foo()
  rec.clay(1,9):
    foo()
  rec.clay(1,9):
    foo()
```

and crashes with SEGV.

**Comment by jckarter** [comment]
To detect trivial recursion, it would need to know when functions are pure. In the general case, there's the halting problem.

**Comment by jckarter** [comment]
A more specific thing to disallow would be evaluating a function as part of an overload predicate for that function, as in your example. That doesn't make sense.
