### ISSUE TITLE
New form for interfacing with LLVM intrinsics

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#405]
LLVM intrinsics have limitations that make `external` a bad fit for manipulating them, and using them incorrectly leads to issues like #283 and #368. Intrinsics can't have pointers taken to them and so can't be represented by `CCodePointers`, and they often require literal arguments. There should perhaps be a special form for binding to LLVM intrinsics, maybe something like:

```
// Bind `i32 @llvm.intrinsic.i32(i32, i1)`, where the i1 argument must be literal
external __llvm__("llvm.intrinsic.i32") intrinsic(foo:Int32, #bar:Bool) : Int32;
```

**Comment by jckarter** [comment]
A better interface might be to have an `__intrinsics__` module, that magically creates intrinsic bindings when imported from, using the `TargetIntrinsicInfo` and `llvm/Intrinsics.h` APIs.

**Comment by jckarter** [comment]
I took a first pass at implementing a magic `__intrinsics__` module: https://github.com/jckarter/clay/compare/intrinsics

It tries to be as automatic as possible, choosing the proper instance from within intrinsic families such as `ctlz.*` based on input types and supporting static arguments to provide LLVM-literal arguments to the intrinsic.  There are some shortcomings. Since LLVM's type system doesn't distinguish signed from unsigned integers, the compiler just propagates all intrinsic returns as unsigned. There are also a handful of LLVM intrinsic families such as `llvm.objectsize.*` for which the proper instance and return type cannot be deduced from the input types, so there would need to be some way to explicitly specify the desired instance in some cases.

**Comment by stepancheg** [comment]
`__llvm_intrinsics__` could be a better name, because `ModuleName` or `arrayRef` are also intrinsics.

**Comment by jckarter** [comment]
Clay calls those "primitives" rather than "intrinsics", but I agree the distinction is fine.

**Comment by jckarter** [comment]
I merged my `__intrinsics__` implementation.
