### ISSUE TITLE
Make normal procedures non-overloadable; require `define` for overloadable procedures

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#406]
A function defined with a body, such as `foo(x) = x + 1;`, is currently equivalent to `define foo; overload foo(x) = x + 1;`. It would be clearer if functions that are intended to be overloaded were required to be created with `define` and then `overload`ed explicitly.

**Comment by stepancheg** [comment]
I'll do it.

**Comment by jckarter** [comment]
@stepancheg An alternative to your `open`/`close` proposal that I think would cover most use cases would be to make overloadability private or public. Something like your `SignedInteger?` example should be public, but not publicly overloadable. So maybe you could say:

```
define SignedInteger?(#T) : Bool private overload;
overload SignedInteger?(T) = false;
overload SignedInteger?(#Int8) = true;
/* ... */
```

**Comment by ghost** [comment]
Public by default?

**Comment by jckarter** [comment]
Public by default seems alright by me.
