### ISSUE TITLE
collections top level module

### ISSUE THREAD

**Issue by stepancheg** [jckarter/clay#439]
lib-clay has too many top-level modules. It is hard to discover what utilities clay has.

I propose container top-level module 'collections' which should contain current modules:
- collections.any
- collections.algorithms
- collections.deques
- collections.hashmaps
- collections.queues
- collections.sequences
- collections.sharedpointers
- collections.strings
- collections.uniquepointers
- collections.vectors

Although any, sharedpointers, uniquepointers and strings are not really "collections", name collections is OK to me, I cannot think of better name.

**Comment by galchinsky** [comment]
In haskell it is named Data. Data.List etc.

**Comment by stepancheg** [comment]
@galchinsky I like "data".

**Comment by jckarter** [comment]
"Dara" sounds good. Unique and shared pointers should probably go somewhere else though; maybe fold them into memory.

**Comment by stepancheg** [comment]
Moved in 453ab5986ae33f5b17da38e5ae5563c5040ba584. *pointers left where they were.
