### ISSUE TITLE
bindgen doesn't check if parsed identifiers conflict with clay keywords

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#49]
Example, test.h:

``` c
struct foo {
    int external;
};
```

produces the following code:

```
/* automatically generated by clay-bindgen */

record Struct_foo (
    external : Int,
);
```

which fails with a parse error.

I'm not sure what the correct course of action would be. Maybe mangle everything that clashes with keywords to something like `originallyExternal`?

**Comment by jckarter** [comment]
Oops. The old bindgen suffixed an underscore to C identifiers that are Clay keywords.

**Comment by jckarter** [comment]
@Blei This and #48 should be fixed now. Let me know how it works with unix/generated on Linux.
