### ISSUE TITLE
cmake doesn't pick the correct python on arch linux

### ISSUE THREAD

**Issue by solson** [jckarter/clay#53]
On Arch Linux, cmake picks `/usr/bin/python`, which is a symlink to `/usr/bin/python3`, but the python script that `make test` uses needs `/usr/bin/python2`.

A simple workaround is to edit CMakeCache.txt and change it to the right python, but it took a little digging to find that as a cmake noob.

**Comment by jckarter** [comment]
I'm not a big python guy. Is there an idiomatic way of choosing a particular python version in the `#!` line?

**Comment by solson** [comment]
I'm not a python guy either, but I think `#!/usr/bin/env python2` would work on most linux distros.

**Comment by solson** [comment]
Actually it might be more portable to use the exact version, for example `#!/usr/bin/env python2.7`. From what I've read it seems like more distros have binaries like that.

**Comment by jckarter** [comment]
Yeah, brew on macosx only installs `python2.7` but no `python2`. I'll use that then.

**Comment by jckarter** [comment]
I wasn't sure how exactly to cajole cmake's FindPythonInterp into favoring 2.7, but I hope this will work. Let me know how it goes, @tsion.

**Comment by solson** [comment]
I still get `-- Found PythonInterp: /usr/bin/python (found version "3.2.2")` from cmake unfortunately.

**Comment by solson** [comment]
I just found out I can force it by running `cmake -D PYTHON_EXECUTABLE=/usr/bin/python2 -G "Unix Makefiles" ../`.

**Comment by jckarter** [comment]
@tsion I picked up Elrood's patch. Let me know if it works for you now.

**Comment by solson** [comment]
Cool, thanks, it works now. 

It was a little confusing at first because the cmake output still only mentioned finding Python 3 since the code that Elrood added doesn't output anything, but that's not a big issue.
