### ISSUE TITLE
Generalize 'and' and 'or' operators

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#57]
It would be useful to be able to overload `and` and `or` for `Maybe`, `Either`, and other monadic types:

```
var x = maybeA() and maybeB() and maybeC(); // short-circuit maybe chaining (aka ">>=")
var y = maybeA() or maybeB(); // maybe alternation (aka "mplus")
var z = maybeA() or 0; // maybe unpack with default
```

**Comment by ghost** [comment]
What's your stance on using 'and', 'or', 'not' keywords instead of the C-like operators (&&,||,!) ?  Is this a preference or just a carry over from the Pascal syntax?

**Comment by jckarter** [comment]
I kind of like `and` and `or` because they're prettier and easier to type than the C operators.

**Comment by ghost** [comment]
Could the variadic-op set-up be used for <code>and</code>  &  <code>or</code> . . .?

**Comment by jckarter** [comment]
I'm not sure. I'd like the short-circuit behavior to be inherent in the way `and` and `or` desugar, perhaps by having the right-hand side desugar as a lambda.

**Comment by jckarter** [comment]
This probably isn't necessary anymore, since you could easily define your own `&&` and `||` as `alias` functions that do whatever you want.
