### ISSUE TITLE
bindgen: no declaration of opaque structs on typedef

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#66]
The following struct is defined/typedefd in glib/gthread.h:

``` c
typedef struct _GMutex          GMutex;
```

That's all there is; it's supposed to be opaque.

Bindgen on the other hand generates the following failing code:

```
alias GMutex = Struct__GMutex;
```

I thinks something like `alias Struct__GMutex = Opaque;` or `alias GMutex = Opaque;` should be generated.

**Comment by jckarter** [comment]
@Blei I tried generating the following file with bindgen as-is:

```
typedef struct _GMutex          GMutex;
```

and I got:

```

/* automatically generated by clay-bindgen */

alias Struct__GMutex = Opaque;

alias GMutex = Struct__GMutex;
```

Is `struct _GMutex` defined in another header that doesn't match your `-match` filters?

**Comment by jckarter** [comment]
@Blei Just in case, I pushed a patch that ensures that opaque types get visited for typedefs (as well as a patch to fix your other bug, which I did reproduce). Let me know if it helps.

**Comment by Blei** [comment]
Works perfectly. Thanks!
