### ISSUE TITLE
inconvenient handling of enums by bindgen

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#71]
The following C header:

``` c
typedef enum {
  FOO = 1,
} my_enum;

void callWithEnum(my_enum e);
```

gets generated as:

```
/* automatically generated by clay-bindgen */

alias Enum_Unnamed1 = UInt;
alias FOO = 1;

alias my_enum = Opaque /* unknown EnumDecl  */;

external (cdecl) callWithEnum(arg0:my_enum) : ;
```

The problem is that `callWithEnum` expects a `my_enum` value as input. This is an alias to `Opaque` which is a `Byte`. The generated enums on the other hand are `Int`s, so type checking fails. It's of course possible to cast all enum values by hand, but it's very inconvenient.

How about something like:

```
alias Enum_Unnamed1 = UInt;
alias FOO = Enum_Unnamed1(1);
alias my_enum = Enum_Unnamed1;
```

**Comment by Blei** [comment]
Oh, I just saw that this is a duplicate of #21. Sorry about that.

**Comment by jckarter** [comment]
It looks like a real bug in there. `my_enum` shouldn't be getting generated as `Opaque`, it should be aliased to the unnamed enum.
