### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#82]
C programmers love 'em, we should have 'em.
- Change the dereference operator from `a^` to `a@`.
- Add the following desugars:
  - `~a` -> `bitnot(a)`
  - `a & b` -> `bitand(a, b)`
  - `a | b` -> `bitor(a, b)`
  - `a ^ b` -> `bitxor(a, b)`
  - `a << b` -> `bitshl(a, b)`
  - `a >> b` -> `bitshr(a, b)`
  - Rust's precedence rules for these operators is better than C's.

**Comment by jckarter** [comment]
Infix `&`, `|`, `<<`, and `>>` are available, but infix `^` would conflict with the postfix dereference operator. Need to either change the deref operator and use `^` for xor, or pick another random symbol for xor.

**Comment by ghost** [comment]
I'm all for keeping the bitwise operators in-line with C, I think most programmers would be familiar with this syntax.

~ (bitnot)
& (bitand)
| (bitor)
<< (bitshl)

> > (bitshr)
> > ^ (bitxor)

Using the postfix ^ for dereferencing was a big improvement over C pointer syntax, but my preference for dereferencing would just be the array syntax minus the index . . . . ptr[] . . .  would this work?  Failing that some other easily available character, ¬, ?, @, . . .

**Comment by jckarter** [comment]
`[]` is an interesting idea, but it might be too bulky. I was thinking of trying postfix `!` for dereference, at least to start out with.

**Comment by ghost** [comment]
I suppose another issue is <code>&</code> doubling up for address return and bitand. Are you considering changing the address operator? 

Maybe 
<code>ref b = @a</code> 
<code>var c = b!</code>
or
<code>ref b = @a</code> 
<code>var c = b?</code>

As a single character dereferencing operator the <code>?</code> seems fairly intuitive. Although I guess this is being used as a convention for boolean functions. While the <code>!</code> is compact it does seem like a random choice.

**Comment by jckarter** [comment]
Well, the address operator is prefix, so there's no ambiguity between `&a` and `a & b`, like in C.

**Comment by jckarter** [comment]
Actually postfix `!` won't work too because of the `!=` operator—`a! = b;` and `a != b;` would be ambiguous. How about postfix `@`? The pronunciation "at" sounds vaguely pointer-related.

**Comment by ghost** [comment]
Hmm, I can't think of a very good reason not to use that.

Is there some clear rationale  for using a postfix operator? The only issue I ever really had with C pointer syntax was overuse of the <code>*</code>. Keeping all unary operators prefix has some merit with regards to language consistency. I think this is something that has seen much debate in the C/C++ community (++i vs i++, etc).

**Comment by jckarter** [comment]
Postfix dereference composes naturally with indexing and field accessors, which are also postfix. C/C++'s prefix dereference necessitates the `a->b` operator as shorthand for `(*a).b`. In Clay (or Pascal, whence it stole the syntax) `a^.b` just works, and is clearly distinct from `a.b^` or `a^^.b`.

**Comment by ghost** [comment]
OK, makes sense.

Based on code cleanliness: 

<code>ptrToRecord!.recField</code>
<code>ptrToRecord?.recField</code>
<code>ptrToRecord¬.recField</code>
<code>ptrToRecord[].recField</code>
<code>ptrToRecord~.recField</code>
<code>ptrToRecord@.recField</code>

<code>ptrToRecord!!.recField</code>
<code>ptrToRecord??.recField</code>
<code>ptrToRecord¬¬.recField</code>
<code>ptrToRecord[][].recField</code>
<code>ptrToRecord~~.recField</code>
<code>ptrToRecord@@.recField</code>

I would favour either <code>ptr@</code>, <code>ptr~</code> or <code>ptr¬</code>. Is the negation symbol earmarked for anything else? I would have actually prefer to use the negation symbol over the tilde for 'bitnot' and tilde for deref, but I guess that depends how C-like you want the bitwise operators to be.

**Comment by jckarter** [comment]
`@` seems like the best choice to me for dereference, since it's ASCII, it's somewhat mnemonic and doesn't have any preconceived meaning in C.

**Comment by ghost** [comment]
OK, convinced. +1 for <code>@</code> as deref operator.

**Comment by ghost** [comment]
I've had a go at adding the bitwise operators and made the change to the deref operator - see latest commit.

**Comment by jckarter** [comment]
Change looks good. I think Rust's precedence rules are better though—bitwise and, or, and xor should have higher precedence than the relational operators. `(x & 3) == 3` is more common than `x & (3 == 3)`. I also don't want to break the syntax for 0.1 anymore, so if you could move this into a separate branch, I can pull it when I start on 0.2. Thanks for doing the legwork here!

**Comment by ghost** [comment]
bitwise-ops branch created and precedence updated to mirror Rust.

**Comment by jckarter** [comment]
Excellent. So I don't forget about your branch, you could open a pull request for it, and then I can close this ticket. Thanks again.

**Comment by jckarter** [comment]
Fixed in #93
