### ISSUE TITLE
recursive alias __ARG__ expansion fails

### ISSUE THREAD

**Issue by Blei** [jckarter/clay#89]
Consider the following code:

```
alias foo1(foo) {
    return __ARG__ foo;
}

alias foo2(foo) {
    return foo1(foo);
}

main() {
    println(foo1(1 + 1));
    println(foo2(1 + 1));
}
```

This produces as output:

```
1 + 1
foo
```

I'm not sure if this is how it's supposed to be, but I expected that the same output (`1 + 1`) would be returned in both cases. If I misunderstood the supposed behaviour, please disregard this bug report :).

**Comment by jckarter** [comment]
Unfortunately `__ARG__` only goes one level deep. foo1() sees the expression `foo` passed from foo2() and stringizes that. If you need to pass the original string down a level, you'll have to pass `__ARG__ foo` as a separate argument.
