### ISSUE TITLE
Rename 'inline' attribute to 'trivial'

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#95]
That more accurately captures the intent of the attribute.

**Comment by ghost** [comment]
hmm, "trivial" sounds like an emotional standpoint to me, not telling me much more, while "inline" at least explains to me what will (possibly) happen with this function.

what i mean boils down to:
- inline is a technical term about the wished procedure
- trivial is a measuring term and secondary to the case

**Comment by jckarter** [comment]
Forced inlining isn't very useful and is intended for trivial overloads that would just be noise in the debug information or the symbol table. The more common meaning of `inline` and `noinline` as hints rather than edicts is more generally useful, since modern optimizers are better at making inline decisions than humans most of the time.

**Comment by ghost** [comment]
I truly mean the terms as such ;) I absolutely disagree on what you wrote atop: "That more accurately captures the intent of the attribute." That's what my critique is about. To me, "trivial" doesn't express any intent except of downgrading ;) I'd not want to type that in a programming language.

**Comment by jckarter** [comment]
Done by @agemogolk in #301
